# http://module-build.sourceforge.net/META-spec.html
name:         Win32-MediaPlayer
version:      0.3
version_from: lib/Win32/MediaPlayer.pm
installdirs:  site
requires:
    Win32::API:         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
